### ISSUE TITLE
On square grids, the code tends to find the same fill words up and across

### ISSUE THREAD

**Issue by bsugerman** [jsgonsette/Wizium#6]
This is a great code, and about 8x faster than what I had coded up in pure python (not too surprising). However, below is just one example of many different results that I've gotten when running Wizium on an empty square grid:

          BOLANCI
          OHANIAN
          LAAGERS
          ANGELIA
          NIELSON
          CARIOLE
          INSANER

It looks like the solver could use some logic to keep from using the same words down and across?

**Comment by jsgonsette** [comment]
This is a known problem that I didn't cope with at the time I wrote this project, 17 years ago :-)
A few people have already contacted me about the same subject, but this is only a real issue for square grids without blocks.


The problem is that its resolution is not easy because of the way the grids are constructed.
In fact, a whole series of words are managed **_explicitly_** (the words placed on the grid iteratively), while others appear **_implicitly_** (by stacking 'n' words, words appear perpendicularly)
What I mean by this is that during the construction of the grid, all **explicit** words are known and managed in the backtracking tree, while all others "just appear" but are not known in advance .

Therefore, even if it is simple to prevent two identical words from being placed, it is much more difficult for a word which appears perpendicular to them to be reused.
Certainly it is feasible, but it is necessary to implement a particular logic to manage it.

The big steps of the solution are:
1) add a flag to each word in the dictionary to know if the word has already been used or not
2) prevent the dictionary from returning a word whose flag is set
3) manage the flag for each word placed (or removed) explicitly on the grid
4) check words appearing implicitly doesn't conflict with the flagged one

steps 1-2 should be very simple to implement.
step 3 requires a minimum understanding of the logic of the solvers
step 4 requires a lot more understanding of the solver logic.

I don't plane to update this project anytime soon, but I would be happy to integrate the solution that anyone would like to develop on that matter.
