### ISSUE TITLE
Support for barred grids

### ISSUE THREAD

**Issue by adomasbaliuka** [jsgonsette/Wizium#7]
Do you think the project can be modified to also support barred grids? Are you interested in supporting them?
If it's straightforward, I might try to implement it myself.

**Comment by jsgonsette** [comment]
Yes it can definitively be updated to support a new kind of grid. The overall logic of the solver should not be impacted, only the way words are ended on bars instead of blocks. I have no intention to implement such modification myself but don't hesitate to contact me if you have any technical question.
