### ISSUE TITLE
Some feedback: Get chosen words list? and issues when generating

### ISSUE THREAD

**Issue by lfdversluis** [jsgonsette/Wizium#8]
Thanks for the library, it works quite well. I have some feedback, not sure if the project is still maintained.

1. Can the python wrapper return the list of words eventually used in the crossword puzzle? I think it would be helpful if you want to generate the hints and numbers.
2. The status (draw() function) doesn't appear to be filled it. I just get a grid shown with # and .
3. If the library couldn't generate a crossword, is it possible to provide a reason? Especially if there is a lack of words of a certain length, that could be very helpful. I ran into this as there aren't readily and available lists of words + hints, I made my own one, but it lacked a bit of 3 letter words.

**Comment by jsgonsette** [comment]
Hello and thanks for the feedback.


This library is not maintained anymore but I can provide advice to anyone wanting to improve it.

1) this is easily doable since it is just a matter of scanning the grid content after a call to Python def grid_read (self).
2) I don't see the function you are referring to.
3) If the grid generation could not complete, it only means that the generator ran out of possible words at some given locations and had to backtrack (the algorithm uses backtracking). However, there are so many combinations to test that heuristics may be used to speed up the process. The disadvantage, though, is that such heuristics may inadvertently skip good potential solutions. As such, in case of failure, your only option is to reduce / disable the heuristics, or to change the seed that influence the start position for the search.

```
    def solver_start (self, seed=0, black_mode='DIAG', max_black=0, heuristic_level=-1):
        """Start the grid generation process
        seed            Custom seed for the generation process
        black_mode        'DIAG':
                        'ANY':
                        'TWO':
                        'SINGLE':
        max_black        Max. number of black boxes that can be added to the grid
        heuristic_level    Heuristic strength. -1: no heuristic
```

Don't forget that the generation of crossword grid is a NP-Hard problem. Scanning cleverly all the possibilities is all that you can do. And when you don't find any solution, then, either there is no solution, or the heuristic process is to be blamed. In the second case, changing the `seed` and start again may be a good option.

**Comment by lfdversluis** [comment]
Thanks for the reply!

1. Yeah true, that works. 
2. The example python code calls draw() during the while() loop, but for me it always prints the initial grid.
3. I don't know if it's fully working.
I just created some simple grids now and it fails to generate a valid grid, despite there being possibilities. I tried setting heuristic_level=-1, but to no avail. Perhaps a bug in the back tracking?

I'll try my hand at a brute-force approach with backtracking since I am not that good with c++. Thanks :)
